### ISSUE TITLE
Consider Renaming Executive MetaScrum to Executive Product Leadership Team (EPLT)

### ISSUE THREAD

**Issue by DaveW001** [scrumatscale/official-guide#103]
I'd propose the term 'executive metascrum' doesn't quickly convey the focus of what the team does. Consider using one of the following alternative names:

- Executive Product Leadership Team (EPLT)
- Executive Product Owner Team (EPOT)

In my view, both alternatives are more intuitive and more parallel with the corollary Executive Action Team.

**Comment by Jessica-Larsen** [comment]
Have renamed to "executive metascrum team" do you think this helps clarify the intent? @DaveW001

**Comment by DaveW001** [comment]
Certainly better, @Jessica-Larsen. In my view, part of the challenge is the term "metascrum" which doesn't easily convey a sense of / relationship to product ownership. But if others don't see that as an issue, I certainly wouldn't press the concern.
