### ISSUE TITLE
Assuring the organic nature of the SoS is maintained + Dev Team's autonomy

### ISSUE THREAD

**Issue by HeitorRoriz** [scrumatscale/official-guide#104]
Suggestion to be added to the SoS scaling paragraph:

Scaling
Scaling the SoS
Depending upon the size of the organization or implementation, more than one SoS may be needed to deliver a very complex product. In such cases, a Scrum of Scrum of Scrums (SoSoS) can be created out of multiple Scrums of Scrums. The SoSoS is an organic pattern of Scrum Teams which is infinitely scalable. Each SoSoS should have SoSoSMs and scaled versions of each artifact & event. **Note that the organic nature of the SoS pattern needs to be maintained when scaling to more SoSs, therefore attention to not removing a Development Team's autonomy is crucial while scaling the SoS.**

**Comment by scrumatscale** [comment]
Thank you for the suggestion! While we appreciate the importance of team autonomy, we don't quite view this as interdependent with organic scaling. This is a good point to make in class, or when teaching/coaching on Scrum@Scale, but we're not sure it makes sense to include in the guide.
