### ISSUE TITLE
Pg. 10 Sentence fragment: "Chang-ing direction of the organization, having to fire 20"

### ISSUE THREAD

**Issue by Jon-Jorgensen** [scrumatscale/official-guide#109]
I have already distributed version 1.05 with this issue to my clients CIO and executive directors, who are not looking to fire anyone, as a matter of doing Scrum@Scale.  So, this is an unfortunate issue for me in the here and now.

I would like to move forward with an Agile Transformation, and possibly a future S@S Case Study, so the sooner this gets fixed, and the version revved, the better for all of us.

If you have trouble finding the sentence fragment I'm referring to, please read the 2nd to last paragraph on page 10 related to the MetaScrum Event.  You will find it reads, "Chang-ing direction of the organization, having to fire 20"

**Comment by alexsutherland** [comment]
Looks like @jeffsutherland eliminated this in this commit https://github.com/scrumatscale/official-guide/commit/b5a992005f888c0730b04458eb3f685e58e5c110, and that it came into the guide at part of the mass edits from the Train the Trainer course in October.  That change should get propagated into the PDF and the website on Monday.
