### ISSUE TITLE
Facilitate the MetaScrum event (see below) 

### ISSUE THREAD

**Issue by dphanson** [scrumatscale/official-guide#126]
Documentation is confusing where lists one of the Chief Product Owner's responsibilities as "Facilitate the Meta Scrum event (see below)".  Below is documentation describing the Executive Meta Scrum event, not the Meta Scrum.  Definition of the Meta Scrum is largely assumed as following the "MetaScrum pattern".  Diagrams all assume at least three levels, with MS and EMS (as well as SoS and EAT).  If SoS and EAT warrant separate discussion, I believe MS and EMS also warrant separate discussion.

**Comment by scrumatscale** [comment]
Hi @dphanson Thank you for taking the time to provide your feedback and help improve the clarity of the guide. 
While the EMS is a "zoomed out" version of the MS, and essentially they operate the same way, the correlation between them and a SoS SDS and EAT are not equivalent. The EAT has very different accountabilities than the attendees at an SDS from either the SoS or SoSoS perspective. For example, owning the Transformation Backlog. This is why the SoS SDS and EAT have separate passages, whereas the EMS pattern simply being a derivative of the MS pattern, does not.

**Comment by dphanson** [comment]
Might it be useful to add a section defining the MetaScrum, with some explanation of the MetaScrum pattern, as opposed to simply referencing the Scrum patterns book with a footnote (^5)?

> _Event: MetaScrum_

The patterns book has a 5 page discussion.  Perhaps the community would benefit from a one paragraph summary in the Scrum@Scale Guide.
