### ISSUE TITLE
Scaled Events (Daily, Retro clear; Planning, Review not clear)

### ISSUE THREAD

**Issue by dphanson** [scrumatscale/official-guide#127]
Guide calls out the need to scale all the events, and clearly marks the Scaled Daily Scrum and Scaled Retro with "Event: ", but then omits calling out a scaled planning and review.  If this is intentional (for us to figure out), then I'd recommend clearly saying so.  The MetaScrum is not explicitly documented, but seems that would be the scaled planning event.  This leaves the scaled review without a recommendation.  Seems that should include the whole PO Team with stakeholders plus the SoS Master and representation from each Scrum team, at a minimum.

**Comment by scrumatscale** [comment]
Hi @dphanson thank you for the feedback. In the latest version of the guide, each event is explicitly called out (page 8): "Scaling the Events and Roles
If a Scrum of Scrums (SoS) operates as a Scrum Team, then it needs to scale the Scrum Events and the teams’ corresponding accountabilities. To coordinate the “how” in every Sprint, a SoS will need to hold scaled versions of the Daily Scrum and Sprint Retrospective. To coordinate the “what” in every Sprint, a SoS will need to hold scaled versions of Sprint Planning and a Sprint Review. As an ongoing practice, Backlog Refinement will also need to be done at scale.

The scaled versions of the Daily Scrum and Retrospective are facilitated by a Scrum Master for the group, called the Scrum of Scrums Master (SoSM). The scaled versions of the Sprint Review and Backlog Refinement are facilitated by a Product Owner Team guided by a Chief Product Owner (CPO). The scaled version of Sprint Planning is held with the Product Owner Team and the Scrum Masters. The Product Owner Team gains insight into what will be delivered in the current Sprint and the Scrum Masters gain insight into capacity and technical capabilities. The roles of Scrum of Scrums Master and Chief Product Owner scale into the leadership groups which then drive their corresponding cycles, satisfying the components of Scrum@Scale." 

The PO Team holds scaled versions of planning, refinement and review. This may be done during the MetaScrum, or separately. The guide intentionally is non-prescriptive on this front as it will depend on the specific concerns and context of the organization.

**Comment by dphanson** [comment]
Have you considered adding a similar clarifying statement in the Scrum@Scale guide?  Your final comment to me helps clarify the intentional ambiguity, but I wonder if others would have the same question.  

> "The PO Team holds scaled versions of planning, refinement and review. This may be done during the MetaScrum, or separately. The guide intentionally is non-prescriptive on this front as it will depend on the specific concerns and context of the organization."

I was aware of the section introducing the events, as you copied in your response, but was trying to understand why only two of the events went on to be clearly defined in subsequent sections, while the other two were not.

Events detailed with section headers:
> **Event: The Scaled Daily Scrum (SDS)**
> **Event: The Scaled Retrospective**

Events **not** specified with similar sections headers: 
> _Event: The Scaled Planning_
> _Event: The Scaled Review_

Thank you for clarifying this intentional ambiguity.
