### ISSUE TITLE
Indirect references to 'EMS as a Team' needs update

### ISSUE THREAD

**Issue by shijopaul** [scrumatscale/official-guide#135]
Most of the places, it is very clear that EMS is an event. 

But, under the "Some Notes on Organizational Design" section, the following note can create some confusion that the EMS is a Team, just like EAT.

"A final note on the representation of the Executive Action Team and the Executive MetaScrum: In this diagram, they are shown as overlapping since some members sit on both of the **teams**. In very small organizations or implementations, the Executive Action Team and the Executive MetaScrum may consist entirely of the **same team members**." << highlighted the part which creates confusion that EMS is also a Team.

I would recommend we change this to something like below:
"A final note on the representation of the Executive Action Team and the Executive MetaScrum: In this diagram, they are shown as overlapping since some members sit on both **EAT and EMS**. In very small organizations or implementations, the Executive Action Team and the Executive MetaScrum **event** may consist entirely of the **same members**."

**Comment by scrumatscale** [comment]
Thank you @shijopaul! we agree with the suggestion and will update the guide to reflect this clarification shortly.
