### ISSUE TITLE
Frequency of the Scaled Daily Scrum

### ISSUE THREAD

**Issue by shijopaul** [scrumatscale/official-guide#137]
It is clear in the S@S guide that the "Scaled Daily Scrum event mirrors the Daily Scrum" and that "Is time-boxed to 15 minutes or less".

But, it does not explicitly say that the event happens daily. While it is understood, it is better to clarify that explicitly like in Scrum guide:
"to reduce complexity, it is held at the same time and place every working day of the Sprint."

**Comment by scrumatscale** [comment]
Hi Shijo, 

Thanks for the feedback. In this case, while it may be true that holding the SDS daily is optimal, in practice, this is not always possible or even needed. Hence, we consider the term "Daily" in the name of the event, and the sentence that it "mirrors the Daily Scrum" sufficient.
