### ISSUE TITLE
Team Product Owner

### ISSUE THREAD

**Issue by angldjhnsn** [scrumatscale/official-guide#14]
It seems there is opportunity to revisit "team PO".  It's the source of  concern in the CST community and causing immediate dismissal of S@S.  It lends itself to the behavior of "take a business analyst and call them team PO".  The Scrum Guide seems clear about the level of authority that is needed for a PO.  Having a "team level PO" (which 'team PO' suggests whether we like it or not), gets us back into Scrummerfall having a BA acting as go between who is not really empowered.  Seems like a simple change to course correct to PO in every sense of the word and focus on CPO as more strategic with PO more tactical but still a PO in the sense of what's conveyed in the Scrum Guide.  Would also bring a lot of goodwill about in the very community that this was introduced to in April.

**Comment by alexsutherland** [comment]
I'm not completely clear on what change you are suggesting.  Are you advocating that team level Product Owners not be part of Scrum@Scale and that the role isn't needed, or are you saying that the guide doesn't clearly convey that a team level product owner has all of the authority and responsibility of a product owner as defined in the Scrum guide and complete control over their teams backlog?

The latter is definitely our goal and if that is not the case we should make that more clear.  In S@S the team product owner has complete authority over his or her product backlog and is a product owner exactly as described in the Scrum guide.

The Scrum Guide says: "The Scrum Team consists of a Product Owner, the Development Team, and a Scrum Master."  We feel that following the Scrum guide is best and that in practice most companies suffer from not have enough highly effective and engaged product owners.  Very few companies/teams that I have seen suffer from having overly clear prioritization, expression of vision, understanding of value and of customer need.  We've seen this work well in practice, even in a situation with a single product that hundreds of teams are working on, a good example: https://www.scruminc.com/wp-content/uploads/2017/02/Release-version_Owning-the-Sky-with-Agile.pdf,".

Regarding your point of taking an untrained business analyst and calling them a PO: I don't think the fact that some companies have a lack of good Product Owners or that they put incompetent people in the role should be the basis for removing a critical part of the Scrum team and going against the Scrum Guide at the single team level.

Team level POs have complete authority and accountability over their teams backlog and team level SMs have the same over their team's process.  We believe that some stories and priorities come from the top down (a product vision or need is created by leadership or a CPO or metascrum team and disseminated to groups of teams working in tandem to make that vision a reality) AND from the bottom up (a PO who is engaging with his or her customers at the direct level that they interact with the portion of the product that his or her team has been focused on reacts to customer feedback by independently creating and prioritizing backlog for his or her team). 

If I am misunderstanding what you'd like to see changed, please let me know as I greatly respect and value your feedback.

**Comment by scrumatscale** [comment]
Closing for now, happy to revisit this in the future if you want to re-open Angela

**Comment by angldjhnsn** [comment]
Haven't had 2 min on this so will reopen.
AJ

**Comment by NigelBakerAgileBear** [comment]
+1 for Angelas concern. The major flaw in most Scrum scaled implementations is weak, unempowered Product Owners played by Business Analysts with a traditional management layer making decisions above them. Some of the language in this guide and training seems to encourage this. I would suggest stronger language to enforce the concept that product owners, own the product and are not repurposed "agile BA's".

**Comment by scrumatscale** [comment]
@NigelBakerAgileBear great to have you chime in, is there any specific language in the guide in particular that you or @angldjhnsn feel is the biggest offender here?  I'd love some input on where to focus edits.  Once we've had a chance to edit, I'll post it as a pull request and invite feedback.
