### ISSUE TITLE
Scrum of Scrums Scrum Master acronym

### ISSUE THREAD

**Issue by xdatap1** [scrumatscale/official-guide#21]
Hi,

in the Scrum of Scrums chapter, in the "Roles" part, we introduce the "Scrum of Scrums Scrum Master (SoSM)"
This role name has been updated in the 1.01 version, before it was "Scrum of Scrums Master". 
The acronym, between parenthesis, is still the old one.
I suspect now it should be "SoS-SM" to reflect the recent changes of the text.

Greetings

**Comment by scrumatscale** [comment]
Linguistically we feel the correct parallel is SoSM and that just as with Scrum Master, there is an implied "team" or "group of teams".  We changed it back to SoSM in that one spot so that it is consistent, thank you.
