### ISSUE TITLE
Scrum@Scale Trainers at Scrum Alliance comments 16 Jul 2018 Denver

### ISSUE THREAD

**Issue by jeffsutherland** [scrumatscale/official-guide#23]
Participants will provide dat
AHA Page 8 EAT is accountable for the quality of talent in the organization - Julie
AHA EAT responsible for organizational agility - Dan
AHA What is the ultimate goal - drawing in workshop was helpful 
AHA The MetaScrum is the format for stakeholder input and preferences
CHANGE Scaled Daily Scrum should be SoS Daily Meeting (scales up properly) - Dan
CHANGE Specific language changes to make it tighter, shorter sentences - Dan will provide detail
CHANGE Page 7 graphics should be SoSM (maybe SoSSM), maybe two graphs for people and events - Julie
CHANGE Diagram components with inputs and outputs - Simon
CHANGE Big picture - this plugs into this overview
CHANGE Outcome based metrics - customer satisfaction, financial outcomes, employee engagement

**Comment by jeffsutherland** [comment]
Dan Greening Scrum@Scale Guide
[2018-07-16 SatS Guide Greening Markups.pdf](https://github.com/scrumatscale/official-guide/files/2198977/2018-07-16.SatS.Guide.Greening.Markups.pdf)
 markups attached.

**Comment by jeffsutherland** [comment]
The first thing to do when implementing Scrum@Scale is stated in the Guide as setting up the reference model. However, we want first an EAT that makes sure there is a MetaScrum and implements a reference model. Need to tweak the guide.

**Comment by scrumatscale** [comment]
These were aggregated and applied in this pull request: https://github.com/scrumatscale/official-guide/pull/30, if anyone feels that an important piece of feedback was not properly incorporated please feel free to open a new issue.
