### ISSUE TITLE
S@S Training Comments Cambridge 23-27 Jul 2018

### ISSUE THREAD

**Issue by jeffsutherland** [scrumatscale/official-guide#26]
CHANGE Eugene - SM cycle page 6 - Define the SoSoS Scrum Master
CHANGE - Alex - Scaled Daily Scrum, Scaled Scrum Master, Scaled Backlog Refinement
AHA - scale free architecture, everyone in Scrum
CHANGE - Kiran - add content about systems thinking and organizational design (Mid-Continent)
AHA - changes to Guide 1.01 solved some of my suggested changes
CHANGE - Example 7:30-8:45 Scale Daily Meetings for one company (like SAAB)
AHA - 
CHANGE - SoS creates an increment
CHANGE - start of document could describe how we work through the diagram in a structured way
CHANGE - cascading acronyms are confusing
**CHANGE - inconsistent with Scrum Guide (take stories out of S@S guide)**
CHANGE - Scrum Guide DoD is team (who in Scrum@Scale Guide?)
CHANGE - need glossary
CHANGE - scale free confusing (don't need rules?) What is different between scale free and S@S

**Comment by scrumatscale** [comment]
These were aggregated and applied in this pull request: https://github.com/scrumatscale/official-guide/pull/30, if anyone feels that an important piece of feedback was not properly incorporated please feel free to open a new issue.
