### ISSUE TITLE
Update Portuguese/Brazil translation

### ISSUE THREAD

**Issue by yreiscarrer** [scrumatscale/official-guide#31]
Hi!
I'm very happy with the opportunity to contribute with the Portuguese version, translating the updates of Scrum guide and improving the currently Portuguese version.
For example, there are some typing errors at the Portuguese BR version. But the file is in pdf and I can't edit it. How can I go on? I see some options:
-If you have a ".tex" document, please share it and I can edit it
-If you don't have a ".tex" document, I can create one ".tex" version with full content, but I saw that I'm not allowed to upload files
-I can comment as a new issue for all the typing errors and updates, but doesn't seems to be the best approach, because someone else would need to update
-I can "create a new file" at the default repository, but it seems that the ".tex" is more recommend at "readme"
Regards,
Yolanda

**Comment by Jessica-Larsen** [comment]
Hi @yreiscarrer , 
Thank you for your contribution! I'm hoping @rodrigopaulo, who submitted the original Portuguese translation, can help by submitting the .tex file as a pull request. @rodrigopaulo, would you be willing to do that? Thank you!
