### ISSUE TITLE
Change "company" to "organization"

### ISSUE THREAD

**Issue by FischbachP** [scrumatscale/official-guide#39]
In the EMS section is the notion that "the EMS owns
the organizational vision and sets the strategic priorities for the whole
company, aligning all the teams around common goals." (453)

This is the only mention of the word "company". Should this be changed to "organization"?

**Comment by PaulaKvedaras** [comment]
I agree it would be better organization instead of company,

**Comment by jeffsutherland** [comment]
I removed the work "company" from the guide.
Jeff

-- 
Jeff Sutherland, Ph.D. 
Founder and Chairman, Scrum, Inc.
www.scruminc.com ( http://www.scruminc.com/ )
One Broadway, 14th Floor
Cambridge, MA 02142
P +1 (617) 947 7400 

Scrum@Scale Guide
HBR paper on Scrum: Embracing Agile ( https://hbr.org/2016/05/embracing-agile ) 
Book: Scrum: The Art of Doing Twice the Work in Half the Time ( http://www.amazon.com/Scrum-Doing-Twice-Work-Half/dp/038534645X )
Courses: scruminc.com/scrum-courses-and-training/ ( http://www.scruminc.com/scrum-courses-and-training/ )
Twitter: jeffsutherland  Skype: jeffsutherland
jeff@scruminc.com ( jeff.sutherland@scruminc.com )

**Comment by PaulaKvedaras** [comment]
Excellent! Thank you! I will also change it in the version in Spanish I submitted yesterday!

**Comment by scrumatscale** [comment]
This was incorporate in Jeff's pull request #43
