### ISSUE TITLE
Missing description for some of the components in the s@s framework

### ISSUE THREAD

**Issue by MirkoKleiner** [scrumatscale/official-guide#47]
It’s a bit confusing, that not all of the components are described in the s@s guide or have at least the same titles.

**Comment by PaulaKvedaras** [comment]
I am sorry, but I do not follow. Which component is not describe?

**Comment by MirkoKleiner** [comment]
thx for asking Paula. If you check the overview graphic with the 2 cycles and compare with the guide you'll find a lot of components not described, or some of them are described but don't have it's own chapter with the same title like e.g. "Deployment" or "Strategic Vision", etc. As I read the s@s guide the first time it was pretty confusing to me and I can imagine that it's even more confusing to other, less experienced people.

**Comment by JoeJustice** [comment]
Agreed Mirko, the current diagram should essentially be the table of contents for the guide. Would you like to propose draft text for some of the missing sections?
