### ISSUE TITLE
Scrum@Scale Guide in Thai

### ISSUE THREAD

**Issue by dahmocadee** [scrumatscale/official-guide#55]
[
[คู่มือ Scrum@Scale .pdf](https://github.com/scrumatscale/official-guide/files/2661865/Scrum.Scale.pdf)
[คู่มือ Scrum@Scale.docx](https://github.com/scrumatscale/official-guide/files/2661866/Scrum.Scale.docx)

](url)

**Comment by dahmocadee** [comment]
Hi, 

Could you please help me to upload the Scrum@Scale Guide in Thai to the website?
Thank you.

All the best,

Dahm M. Hongchai

**Comment by Jessica-Larsen** [comment]
This is merged @dahmocadee. Thanks for your contribution!
