### ISSUE TITLE
Define "Linear Scalability"

### ISSUE THREAD

**Issue by JoeJustice** [scrumatscale/official-guide#58]
In the"Why" section of the guide "Linear Scalability" is introduced but not defined. In business structures, the sentence just before gives the opposite of the definition but this is not made clear- the opposite would be adding teams causes delivery to slow down. I'll propose a definition "doubling the number of teams doubles output or better without degradation of quality or happiness." Please make this definition better or feel free to use it as a starter!

**Comment by Pakort** [comment]
I agree. 
Maybe for a Leader that need to improve and don't know about S@S a user story would be:
"As a Manager/Director, etc. I want to know what Linear Scalability means in my organization so that I can better support and sponsor the transformation process"

**Comment by krbabu** [comment]
To borrow from the study of algorithms, if n engineers work in a project conducted according to Scrum@Scale, the product increment output is O(n) measured, for example, in terms of the number of story points. Ref: https://en.wikipedia.org/wiki/Time_complexity.
Happiness, of course, is another matter. How do we quantify happiness?
