### ISSUE TITLE
Clarify the "Why" from the Executive perspective

### ISSUE THREAD

**Issue by Pakort** [scrumatscale/official-guide#62]
In the "Why Scrum@Scale" section it is explained the why of the framework, but not the why from an executive perspective.
As an Executive level I want to understand the benefits of implementing Scrum@Scale in my organization.

**Comment by chris-is-agile** [comment]
The last paragraph seems to talk a lot about the benefits of Scrum@Scale from an executive stand point. What additional points would be helpful? Maybe a reference to the Scrum@Scale Case Study repository?
