### ISSUE TITLE
Glossary needed

### ISSUE THREAD

**Issue by DanielMezick** [scrumatscale/official-guide#67]
S@S introduces new terminology and in some instances redefines old terminology. A good example of this is the term of art 'Scrum of Scrums," which most readers associate with an Event (the SMs from each team periodically meeting) but is now the name of a Role (a certain Team) in the S@S Guide. Further, the meeting formally called "Scrum of Scrums" that is in common usage today, is now referred to formally to in the S@S Guide as the Scaled Daily Scrum. 

In addition, others here have pointed to the clear need to define essential terms such as [scale free] , [linear scalability] , etc.

In light of the foregoing I am raising the issue of generating a concise Glossary or "Terms of Art" for S@S. I believe we need such a list. Shared word definitions are agreements and as such, are essential.

**Comment by chris-is-agile** [comment]
Yes, please. :)
