### ISSUE TITLE
Consider adding a footnote to clarify terms: [Scrum of Scrums] & [Scaled Daily Scrum]

### ISSUE THREAD

**Issue by DanielMezick** [scrumatscale/official-guide#68]
The term "Scrum of Scrums" is in common usage today and commonly refers to a periodic meeting of team representatives, typically the SMs. This term now has a new meaning (it now refers to a Team, a type of Role and not an Event) and further, the Event has a new name: Scaled Daily Scrum.

In light of the foregoing, I propose that a footnote be added in the text, in addition to any Glossary entry that may appear in the Guide. 

Rationale: Readers are parsing the text and trying to build understanding by reading sequentially, without skipping around. Adding a footnote that disambiguates the term [Scrum of Scrums] when introduced is therefore essential, at least until the new terminology (as expressed in the Guide) catches on.

**Comment by chris-is-agile** [comment]
We agree that some clarification should be brought out. We can make it more clear in the guide with reasoning as opposed to a footnote. But clarity along the use of Scrum of Scrums would be helpful.
