### ISSUE TITLE
Clarity on SoS as team of teams vs an event (as used in past)

### ISSUE THREAD

**Issue by sandeepsnet** [scrumatscale/official-guide#95]
The term SoS (Scrum of Scrum) used in past to denote an event. In the context of S@S, we refer SoS as a team of teams. This differentiation needs to be highlighted in the guide in the introductory paragraph of SoS.

**Comment by DaveW001** [comment]
Recommend we consider moving to the term Scrum of Scrum Teams to help clearly distinguish between the common / previous usage (an event) and the formal usage (a team of teams).
